server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: aggregator-service-route
          uri: lb://AGGREGATOR-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: aggregator-service-cb
                fallbackUri: forward:/fallback/aggregator-service
        - id: cinema-cineworld-service-route
          uri: lb://CINEMA-CINEWORLD-SERVICE
          predicates:
            - Path=/cinema/cineworld/**
          filters:
            - name: CircuitBreaker
              args:
                name: cinema-cineworld-service-cb
                fallbackUri: forward:/fallback/cinema-cineworld-service
        - id: cinema-dundrum-service-route
          uri: lb://CINEMA-DUNDRUM-SERVICE
          predicates:
            - Path=/cinema/dundrum/**
          filters:
            - name: CircuitBreaker
              args:
                name: cinema-dundrum-service-cb
                fallbackUri: forward:/fallback/cinema-dundrum-service
        - id: cinema-ucd-service-route
          uri: lb://CINEMA-UCD-SERVICE
          predicates:
            - Path=/cinema/ucd/**
          filters:
            - name: CircuitBreaker
              args:
                name: cinema-ucd-service-cb
                fallbackUri: forward:/fallback/cinema-ucd-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:eureka-server}:${EUREKA_PORT:8761}/eureka/
