POST http://localhost:8099/cinema/cineworld/reservation/make
Content-Type: application/json

{
    "clientName": "Jane Doe",
    "clientEmail": "jane.doe@ucd.ie",
    "movieId": "CNW001",
    "date": "2022-04-15",
    "showTime": "18:00",
    "tickets": 2,
    "ticketType": "Gold",
    "amount": 30.00
}
    