version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

  eureka-server:
    build: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761

  api-gateway-service:
    build: api-gateway-service
    container_name: api-gateway-service
    ports: 
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_SERVER=eureka-server
    depends_on:
      - eureka-server

  movies-service:
    build: movies-service
    container_name: movies-service
    environment:
      - SERVER_PORT=8081
      - EUREKA_SERVER=eureka-server
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
    depends_on:
      - mongodb
      - eureka-server
