version: "3"

volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # rabbitmq default
      - "15672:15672" # rabbitmq management
      - "15692:15692" # rabbitmq prometheus
    volumes:
      - "./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - rabbitmq-prometheus_grafana:/var/lib/grafana
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"

  node-exporter:
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  mongodb:
    image: mongo:latest
    container_name: mongodb

  broker-service:
    build: broker-service
    container_name: broker-service
    ports:
      - "8099:8099"
    environment:
      - SERVER_PORT=8099
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  cinema-cineworld-service:
    build: cinema-cineworld-service
    container_name: cinema-cineworld-service
    environment:
      - SERVER_PORT=8082
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_DATABASE=cinema-cineworld
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - rabbitmq
      - mongodb

  cinema-dundrum-service:
    build: cinema-dundrum-service
    container_name: cinema-dundrum-service
    environment:
      - SERVER_PORT=8083
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_DATABASE=cinema-dundrum
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - rabbitmq
      - mongodb

  cinema-ucd-service:
    build: cinema-ucd-service
    container_name: cinema-ucd-service
    environment:
      - SERVER_PORT=8084
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_DATABASE=cinema-ucd
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - rabbitmq
      - mongodb
