server:
  port: ${SERVER_PORT}

spring:
  application:
    name: movies-service
  data:
    mongodb:
      database: movies
      host: ${DATABASE_HOST}:${DATABASE_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:${EUREKA_PORT:8761}/eureka/