server:
  port: ${SERVER_PORT}

spring:
  application:
    name: aggregator-service 

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:eureka-server}:${EUREKA_PORT:8761}/eureka/
