spring:
  application:
    name: cinema-dundrum-service

data_file: data/movies.json

amqp:
  exchange: cinema
  request:
    routingKey: request.to.cinema
    serviceOnlyRoutingKey: request.to.cinema.dundrum
  response:
    routingKey: response.from.cinema
